apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-password
  namespace: postgresql
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: postgresql-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: postgresql/root
        property: PASSWORD
    - secretKey: postgres-password
      remoteRef:
        key: postgresql/root
        property: POSTGRES_PASSWORD
    - secretKey: replication-password
      remoteRef:
        key: postgresql/root
        property: REPLICATION_PASSWORD
