apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-root-password
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: minio-root-password
    creationPolicy: Owner
  data:
    - secretKey: root-user
      remoteRef:
        key: minio/root
        property: ROOT_USER
    - secretKey: root-password
      remoteRef:
        key: minio/root
        property: ROOT_PASSWORD
    - secretKey: rootUser
      remoteRef:
        key: minio/root
        property: ROOT_USER
    - secretKey: rootPassword
      remoteRef:
        key: minio/root
        property: ROOT_PASSWORD
