apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgweb-secret
  namespace: pgweb
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-backend
  target:
    name: pgweb-password
    creationPolicy: Owner
  data:
    - secretKey: database-url
      remoteRef:
        key: pgweb/dev
        property: DATABASE_URL
    - secretKey: auth-user
      remoteRef:
        key: pgweb/dev
        property: AUTH_USER
    - secretKey: auth-password
      remoteRef:
        key: pgweb/dev
        property: AUTH_PASSWORD
