apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-cnpg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://gitea0213.kro.kr/bluemayne/databases.git
    targetRevision: main
    path: postgresql-cnpg

  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql-cnpg

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10
